version: 0.0.{build}
branches:
  only:
    - tango-9-lts

image: Visual Studio 2015

environment:
  matrix:
    - platform: win32
      ARCH: win32-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATHOMNI: "/cygdrive/c/Python27/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files (x86)\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
    - platform: x64
      ARCH: x64-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
      MSVCVERSION: v90
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATHOMNI: "/cygdrive/c/Python27/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
    - platform: win32
      ARCH: win32-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010"
      MSVCVERSION: v100
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python33\
      PYTHONPATHOMNI: "/cygdrive/c/Python33/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files (x86)\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
    - platform: x64
      ARCH: x64-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
      MSVCVERSION: v100
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python33-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python33-x64/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
    - platform: x64
      ARCH: x64-msvc12
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      MSVCVERSION: v120
      MSVCYEAR: "vs2013"
      MSVCABR: "13"
      VC_VER: 13.0
      PYTHONPATHOMNI: "/cygdrive/c/Python33-x64/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: v140
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python35-x64\
      PYTHONPATHOMNI: "/cygdrive/c/Python35-x64/python"
      BOOST_ROOT: C:\Libraries\boost_1_63_0
      ZMQ_BASE: C:\projects\libzmq
      IDL_BASE: C:\projects\tangoidl
      IDL_BIN: C:\Program Files\tangoidl
      OMNI_BASE: C:\projects\omniORB-4.2.1
      
init:
  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  #RDP from start
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Update NSIS to support long path
  - ps: (new-object System.Net.WebClient).DownloadFile("https://downloads.sourceforge.net/project/nsis/NSIS%203/3.02.1/nsis-3.02.1-strlen_8192.zip?r=&ts=1512138514&use_mirror=10gbps-io", "C:\projects\nsis-3.02.1-strlen_8192.zip")
  - cmd: cd "C:\projects\"
  - cmd: 7z -y x nsis-3.02.1-strlen_8192.zip -oC:\Program Files (x86)\NSIS
  # Tango IDL
  - cmd: set TANGOIDLDIR=C:\projects\tangoidl
  - cmd: git clone --depth 1 --quiet https://github.com/tango-controls/tango-idl %TANGOIDLDIR%
  - cmd: cd "C:\projects\"
  # Zmq
  - cmd: cd "C:\projects\"
  - cmd: md zeromq
  - cmd: cd "C:\projects\"
  - if %ARCH%==win32-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/kif9t1ni9dorv7ai/artifacts/zmq-4.0.5_%ARCH%.zip
  - if %ARCH%==x64-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/v08rh5ojx3uljbm0/artifacts/zmq-4.0.5_%ARCH%.zip
  - if %ARCH%==win32-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/bfw1w51dmwb4t1s8/artifacts/zmq-4.0.5_%ARCH%.zip
  - if %ARCH%==x64-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/dv6koti648n78wru/artifacts/zmq-4.0.5_%ARCH%.zip
  - if %ARCH%==x64-msvc12 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/92i5i0466vrsf8uf/artifacts/zmq-4.0.5_%ARCH%.zip
  - if %ARCH%==x64-msvc14 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/jlsd4d38c425kumq/artifacts/zmq-4.0.5_%ARCH%.zip
  - cmd: 7z -y x zmq-4.0.5_%ARCH%.zip -oC:\projects\zeromq\
  #- cmd: move C:\projects\zeromq\lib\Release\libzmq*mt-4*.lib C:\projects\zeromq\lib\Release\libzmq.lib
  # OmniOrb
  - cmd: cd "C:\projects\"
  - cmd: md omniorb
  - cmd: cd "C:\projects\"
  - if %ARCH%==win32-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/b3j87c59nps33ga8/artifacts/omniorb-4.2.1_%ARCH%.zip
  - if %ARCH%==x64-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/t0c9a59fr0ixb6to/artifacts/omniorb-4.2.1_%ARCH%.zip
  - if %ARCH%==win32-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/0ywhsy2wnmfw99ia/artifacts/omniorb-4.2.1_%ARCH%.zip
  - if %ARCH%==x64-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/x2sr2c1i0f7hy1cg/artifacts/omniorb-4.2.1_%ARCH%.zip
  - if %ARCH%==x64-msvc12 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/2e8wjs2aalg6cryl/artifacts/omniorb-4.2.1_%ARCH%.zip
  - if %ARCH%==x64-msvc14 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/ry9yevfyjddf6j2e/artifacts/omniorb-4.2.1_%ARCH%.zip
  - cmd: 7z -y x omniorb-4.2.1_%ARCH%.zip -oC:\projects\omniorb\
  #Pthread-Win32
  - cmd: cd "C:\projects\"
  - cmd: md pthreads-win32
  - cmd: cd "C:\projects\"
  - if %ARCH%==win32-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/7aj99tp6e6fvron0/artifacts/pthreads-win32-2.9.1_win32-msvc9.zip
  - if %ARCH%==x64-msvc9 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/pgefsid2t7ma16j6/artifacts/pthreads-win32-2.9.1_x64-msvc9.zip
  - if %ARCH%==win32-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/3hhh3rfhif1lgw0f/artifacts/pthreads-win32-2.9.1_win32-msvc10.zip
  - if %ARCH%==x64-msvc10 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/g6g73i5paldagoc4/artifacts/pthreads-win32-2.9.1_x64-msvc10.zip
  - if %ARCH%==x64-msvc12 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/w4vojpste8j6l823/artifacts/pthreads-win32-2.9.1_x64-msvc12.zip
  - if %ARCH%==x64-msvc14 appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/6tson2rjxm3vgwra/artifacts/pthreads-win32-2.9.1_x64-msvc14.zip
  - cmd: 7z -y x pthreads-win32-2.9.1_%ARCH%.zip -oC:\projects\pthreads-win32\
  #VS2008 patch
  - cmd: cd "C:\projects\"
  - cmd: appveyor DownloadFile https://github.com/menpo/condaci/raw/master/vs2008_patch.zip
  - cmd: 7z -y x vs2008_patch.zip -oC:\projects\vs2008_patch\
  - cmd: if %ARCH%==x64-msvc9 call C:\projects\vs2008_patch\setup_x64.bat
  - cmd: if %ARCH%==x32-msvc9 call C:\projects\vs2008_patch\setup_x86.bat
  - cmd: copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
  
  - cmd: cd "C:\projects\cppTango"
install:
  #copy tree for debug build
  - cmd: cd c:/projects/
  - cmd: md debug_build
  - cmd: xcopy "C:/projects/cppTango" "c:/projects/debug_build" /c /g /d /i /e /r /h /y
  # Setting Visual Compiler
  - cmd: cd "C:\projects\"
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc10 call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc10 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 
  - cmd: if %ARCH%==win32-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  # Tango IDL
  - cmd: cd "C:\projects\tangoidl"
  - cmd: cmake -G "%CMAKE_GENERATOR%"
  - cmd: cmake --build ./ --target install --config Debug
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /Release
  - cmd: cmake --build ./ --target install --config Release  
  # Tango API
  - cmd: cd "C:\projects\cppTango"
  - cmd: set BOOST_ROOT=%BOOST_ROOT%
  - cmd: set ZMQ_BASE=C:/projects/zeromq/
  - cmd: set IDL_BASE=%IDL_BIN%
  - cmd: set OMNI_BASE=C:/projects/omniorb/
  - cmd: set PTHREAD_WIN=C:/projects/pthreads-win32/
  - cmd: if %ARCH%==x64-msvc14 set path=%path%;%PYTHONPATH%
  #- cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE
  #- cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DIDL_BASE="%IDL_BASE%" -DOMNI_BASE="%OMNI_BASE%" -DZMQ_BASE="%ZMQ_BASE%" -DPTHREAD_WIN=%PTHREAD_WIN%
  - cmd: cd c:/projects/debug_build
  #- cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=Debug
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DCMAKE_BUILD_TYPE=Debug -DIDL_BASE="%IDL_BASE%" -DOMNI_BASE="%OMNI_BASE%" -DZMQ_BASE="%ZMQ_BASE%" -DPTHREAD_WIN=%PTHREAD_WIN%

clone_folder: C:\projects\cppTango

build:
  project: C:\projects\cppTango\tango.sln
  verbosity: minimal
  
build_script:
  - cmd: cd C:/projects/cppTango 
  - cmake --build ./ --config Release
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd: cd c:/projects/debug_build
  - cmake --build ./ --config Debug
  #- cmake --build ./ --target install  --config Debug


after_build:
  - cmd: cd C:/projects/cppTango 
  # Generating installer
  - cmd: cpack -G WIX
  - cmd: cpack -G ZIP
  - cmd: cd c:/projects/debug_build
  # Generating installer
  - cmd: cpack -C Debug -G WIX
  - cmd: cpack -C Debug -G ZIP
  #rename x64-msvc10
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_Windows7.1SDK_x64_debug.msi libtango_9.2.6_v100_x64_debug.msi
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_Windows7.1SDK_x64_debug.zip libtango_9.2.6_v100_x64_debug.zip
  - cmd: cd C:/projects/cppTango 
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_Windows7.1SDK_x64.msi libtango_9.2.6_v100_x64.msi
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_Windows7.1SDK_x64.zip libtango_9.2.6_v100_x64.zip
  # copying debug versions for upload
  - cmd: cd c:/projects/debug_build
  - cmd: if %ARCH%==win32-msvc9 move libtango_9.2.6_v90_x86_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==win32-msvc9 move libtango_9.2.6_v90_x86_debug.zip C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc9 move libtango_9.2.6_v90_x64_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc9 move libtango_9.2.6_v90_x64_debug.zip C:/projects/cppTango
  - cmd: if %ARCH%==win32-msvc10 move libtango_9.2.6_v100_x86_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==win32-msvc10 move libtango_9.2.6_v100_x86_debug.zip C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_v100_x64_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc10 move libtango_9.2.6_v100_x64_debug.zip C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc12 move libtango_9.2.6_v120_x64_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc12 move libtango_9.2.6_v120_x64_debug.zip C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc14 move libtango_9.2.6_v140_x64_debug.msi C:/projects/cppTango
  - cmd: if %ARCH%==x64-msvc14 move libtango_9.2.6_v140_x64_debug.zip C:/projects/cppTango


on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_failure:
  #RDP for failure
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.exe
  - path: ./*.zip
  - path: ./*.msi
